name: Deploy backend to Local Server


on:
  push:
    branches:
      - main
    paths:
      - 'coseli/**'
  workflow_dispatch:  # Allows manual trigger


jobs:
  deploy-backend:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          cd /home/coseli/coselinepal/coseli
          npm install

      - name: Build Backend
        run: |
          cd /home/coseli/coselinepal/coseli
          npm run server

      - name: Restart frontend server
        run: |
          cd /home/coseli/coselinepal/coseli
          pm2 stop coseli-backend || true
          pm2 start npm --name "coseli-backend" -- run start