name: Deploy to Local Server


on:
  push:
    branches:
      - main
    paths:
      - 'coseli/**'
  workflow_dispatch:  # Allows manual trigger


jobs:
  deploy-backend:
    if: contains(github.event.head_commit.modified, 'coseli/')
    runs-on: coseli-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: |
          cd coseli
          npm install
      - name: Build backend
        run: |
          cd coseli
          npm run server
      - name: Restart backend server
        run: |
          pm2 stop caseli-backend || true  # Stop if running
          pm2 start npm --name "coseli-backend" -- run start

