name: Deploy backend to Local Server


on:
  push:
    branches:
      - main
    paths:
      - 'coseli/**'
  workflow_dispatch:  # Allows manual trigger


jobs:
  deploy-backend:
    runs-on: self-hosted
    steps:

      - name: Install global dependencies
        run: npm install -g yarn
        
      - name: Install dependencies
        run: |
          cd /home/coseli/coselinepal/coseli
          yarn install

      - name: Build Backend
        run: |
          cd /home/coseli/coselinepal/coseli
          npm run build

      - name: Copy env file
        run: |
          cp /home/coseli/coselinepal/coseli/.env /home/coseli/coselinepal/coseli/.medusa/server/.env
      
      - name: Install dependencies
        run: |
          cd /home/coseli/coselinepal/coseli/.medusa/server
          yarn install

      - name: Restart frontend server
        run: |
          cd /home/coseli/coselinepal/coseli/.medusa/server
          pm2 stop coseli-backend || true
          pm2 start npm --name "coseli-backend" -- run start
