name: Deploy frontend to Local Server


on:
  push:
    branches:
      - main
    paths:
      - 'coseli-storefront/**'
  workflow_dispatch:  # Allows manual trigger


jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
    
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install global dependencies
        run: |
          npm install -g yarn pm2
          
      - name: Install dependencies
        run: |
          cd /home/coseli/coselinepal/coseli-storefront
          npm install


      - name: Build frontend
        run: |
          cd /home/coseli/coselinepal/coseli-storefront
          npm run build

      - name: Restart frontend server
        run: |
          cd /home/coseli/coselinepal/coseli-storefront
          pm2 stop coseli-storefront || true  # Stop if running
          pm2 start npm --name "coseli-storefront" -- run start
